FROM maven:3.6.2-jdk-14-alpine

# copying src of framework  (This location in docker :=> /home/SeleniumTestFramework/src)

COPY src /home/SeleniumTestFramework/src

# copying pom.xml of the framework

COPY pom.xml /home/SeleniumTestFramework

# copying testng.xml of the framework

COPY testng.xml /home/SeleniumTestFramework

# running the ctual command - building 

RUN mvn -f /home/SeleniumTestFramework/pom.xml clean test -Podium=true